Update requirements.txt
ERROR: Cannot install -r requirements.txt (line 29), dbt-core, great-expectations, jsonschema==4.19.0 and pydantic==2.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic==2.3.0
    great-expectations 0.17.23 depends on pydantic>=1.9.2
    dbt-semantic-interfaces 0.2.3 depends on pydantic~=1.10
    The user requested pydantic==2.3.0
    great-expectations 0.17.23 depends on pydantic>=1.9.2
    dbt-semantic-interfaces 0.2.2 depends on pydantic~=1.10
    The user requested jsonschema==4.19.0
    great-expectations 0.17.23 depends on jsonschema>=2.5.1
    altair 4.2.1 depends on jsonschema>=3.0
    dbt-semantic-interfaces 0.2.1 depends on jsonschema~=3.0
    The user requested jsonschema==4.19.0
    great-expectations 0.17.23 depends on jsonschema>=2.5.1
    altair 4.2.1 depends on jsonschema>=3.0
    dbt-semantic-interfaces 0.2.0 depends on jsonschema~=3.0

Alternativa más simple: Eliminar great-expectations
Si prefieres una solución más simple, puedes:
Eliminar la línea great-expectations>=0.17.23 del requirements.txt