Update requirements.txt
# Cambiar esto:
pydantic==2.3.0
jsonschema==4.19.0

# Por esto:
pydantic>=1.10.0,<2.0.0
jsonschema>=3.0.0,<4.0.0

resolver:

ERROR: Cannot install dbt-core, jsonschema==4.19.0 and pydantic==2.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic==2.3.0
    dbt-semantic-interfaces 0.2.3 depends on pydantic~=1.10
    The user requested pydantic==2.3.0
    dbt-semantic-interfaces 0.2.2 depends on pydantic~=1.10
    The user requested jsonschema==4.19.0
    dbt-semantic-interfaces 0.2.1 depends on jsonschema~=3.0
    The user requested jsonschema==4.19.0
    dbt-semantic-interfaces 0.2.0 depends on jsonschema~=3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts